seed_everything: true
trainer:
  log_every_n_steps: 1
  check_val_every_n_epoch: 100
  max_epochs: 1000
  logger:
    class_path: lightning.pytorch.loggers.WandbLogger
    init_args: 
      save_dir: experiments/vae
