name: hidden layers (lognormal)
program: sdtd.vae.main
command:
- ${env}
- ${interpreter}
- -m
- ${program}
- fit
- -c
- sdtd/vae/configs/dataset/lognormal.yaml
- -c
- sdtd/vae/configs/model/sdtd.yaml
- ${args}
method: grid
parameters:
  model.init_args.n_layers_z:
    values: [1, 2, 4, 8]
  data.dataset_cfg.seed:
    value: 42
  model.init_args.output_dim_z:
    value: 1
  model.init_args.hidden_dim_z:
    value: 1
  trainer.check_val_every_n_epoch:
    value: 1
