model:
  class_path: sdtd.vae.lightning_modules.SDTDModule
  init_args:
    output_dim_z: 10
    hidden_dim_z: null
    hidden_dim_z_same_as_output_dim_z: true
    n_layers_z: 2
    alpha: 1.0
    hidden_dim_x: null
    n_layers_x: 1
    activation: 'relu'
    lr: 0.001
    beta_z: 1.0
    beta_w: 1.0
    beta_w_decaying_epochs: null
    beta_w_annealing_epochs: null
